#In this notebook we are going to cover some of the most fundamental concepts of tensors using tensorflow

to cover:

*introduction to tensors 

*getting information from tensors

*manipulatong tensors

*tensors and numpy

*using @tf.function

*using GPU with tensorflow

*exercise to try for myself




In [ ]:
import tensorflow as tf
print(tf.__version__)

2.9.2


In [ ]:
#creating tersors with tf.constant()
scaler = tf.constant(5)
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [ ]:
#check the number of dimensions of a tensor (ndim stands for number of dimensions)
scaler.ndim

0

In [ ]:
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix=tf.constant([[1,2,3],[2,2,2]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [2, 2, 2]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
from numpy import float16
matrix=tf.constant([[1,2,3],[2,2,2],[3,3,3]],dtype=tf.float16)
matrix

<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
array([[1., 2., 3.],
       [2., 2., 2.],
       [3., 3., 3.]], dtype=float16)>

In [ ]:
tensor = tf.constant([[[1,2,2],[2,23,4]],[[3,3,3],[2,2,2]],[[2,2,2],[2,2,2]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  2],
        [ 2, 23,  4]],

       [[ 3,  3,  3],
        [ 2,  2,  2]],

       [[ 2,  2,  2],
        [ 2,  2,  2]]], dtype=int32)>

In [ ]:
tensor.ndim

3

# what we have created so far:
*scalar : a single number

*vector : a number with direction(eg. wind speed and direction)

*matrix : a 2-dimensional array of number

*tensor : an n-dimensional array of numbers (when n can be any number,a 0-dimensional tensor is a scalar)



Creating tensors with tf.variable

In [ ]:
s1=tf.Variable([1,3,2])

In [ ]:
#creatin the ame tensor with variable and constant
changeable=tf.Variable([12,13]);
unchangeable=tf.constant([12,13]);
changeable[0]

<tf.Tensor: shape=(), dtype=int32, numpy=12>

In [ ]:
changeable[1].assign(12)

<tf.Variable 'UnreadVariable' shape=(2,) dtype=int32, numpy=array([12, 12], dtype=int32)>

In [ ]:
# unchangeable[0].assign(14) we cannot do this

In [ ]:
#creating random tensors
# random tensors are tensors of some abitrary size which contain random numbers
import tensorflow as tf
randnum1=tf.random.Generator.from_seed(42)  # set seed for reproducibility
randnum11=tf.random.Generator.from_seed(34)
randnum2=randnum1.normal(shape=(3,2))
randnum22=randnum11.normal(shape=(5,7))
randnum11,randnum2

(<tensorflow.python.ops.stateful_random_ops.Generator at 0x7fa83d485460>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

In [ ]:
import tensorflow as tf
random3=tf.random.Generator.from_seed(2)
randnum3=random3.normal(shape=(3,4))
randnum3

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[-0.1012345 , -0.2744976 ,  1.4204658 ,  1.2609464 ],
       [-0.43640924, -1.9633987 , -0.06452483, -1.056841  ],
       [ 1.0019137 ,  0.6735137 ,  0.06987712, -1.4077919 ]],
      dtype=float32)>

In [ ]:
#shuffle the order of elements in a tensor(valuabe for when you want to shuffle your data so the inherent order doesn't effect learning)
not_shuffle=tf.constant([[12,4,2],
                        [1,3,2],
                        [1,4,2]])
not_shuffle.ndim

2

In [ ]:
tf.random.shuffle(not_shuffle)
tf.random.shuffle(not_shuffle,seed=33)  # it just operational-level seed

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[12,  4,  2],
       [ 1,  4,  2],
       [ 1,  3,  2]], dtype=int32)>

In [ ]:
tf.random.set_seed(43)  # global level seed
tf.random.shuffle(not_shuffle,seed=33)  # it looks like if we want our shuffled tensors to be in the same order
#,we've got to use the global level random seed as well as operation level random seed:
# rule 4 if both the global and the operation seed are set both seeds are used in conjuction to deteremine the ranoom sequenece;

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[12,  4,  2],
       [ 1,  4,  2],
       [ 1,  3,  2]], dtype=int32)>

In [ ]:
import tensorflow as tf
#others ways to make tensors
tf.ones([12,6])  # create a tensor of all ones
# tf.zeros(shape=(3,5))

<tf.Tensor: shape=(12, 6), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
#you can also turn numpy array into tensors
# the main difference between numpy array and tensorflow tensors is that tensors can be run on GPU(much faster)
# for numerical computing
import numpy as np
a=np.arange(1,31,dtype=np.int32)

In [ ]:
A=tf.constant(a,shape=(2,3,5))
B=tf.constant(a)
A,B

(<tf.Tensor: shape=(2, 3, 5), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4,  5],
         [ 6,  7,  8,  9, 10],
         [11, 12, 13, 14, 15]],
 
        [[16, 17, 18, 19, 20],
         [21, 22, 23, 24, 25],
         [26, 27, 28, 29, 30]]], dtype=int32)>,
 <tf.Tensor: shape=(30,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30], dtype=int32)>)

In [ ]:
#getting information from tensors
#attributes:shape,rank,axis or dimension,size
#creating the rank 4 tensor(4 dimension)
rank4=tf.zeros(shape=[2,3,4,6])
rank4[0]
rank4.shape , rank4.ndim , tf.size(rank4)
#rank4

(TensorShape([2, 3, 4, 6]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=144>)

In [ ]:
#get various attributes of our tensors;
print("datatppe of everyelement",rank4.dtype)
print(rank4.shape)
print(rank4.ndim)
print(rank4.shape[0])
print(rank4.shape[-1])
print(tf.size(rank4).numpy())

datatppe of everyelement <dtype: 'float32'>
(2, 3, 4, 6)
4
2
6
144


In [ ]:
# 016 indexing and expanding tensors
# eg ten=[1,2,3,4]
#    ten[:2]
# get the first 2 elements of each dimension
rank4[:2,:2,:2,:2 ]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# get the first element from each dimension from each index except for the final one
rank4[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 6), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
#create a rank 2 tensor(2 dimension)
rank2=tf.constant([[1,2],[3,4]])
rank2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [ ]:
#get the last item of each of our rank 2 tensor
rank2.shape
rank2[:,-1]    # rows*columns

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 4], dtype=int32)>

In [ ]:
#add in extra dimension to our rank 2 tensor
rank3=rank2[...,tf.newaxis]  # instead of :,: -- ...
rank3

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
#alternative 
tf.expand_dims(rank2,axis=0)   # 0 means expand the first axis
tf.expand_dims(rank2,axis=-1)  # -1 means expand the final axis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[1],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
# 017 Manipulating tensors(tensor operation)
#basic operations
tensor1=tf.constant([[1,2,4],[2,2,2]])
tensor+12

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[13, 14, 16],
       [14, 14, 14]], dtype=int32)>

In [ ]:
#orginial tensor is unchanged
tensor1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 4],
       [2, 2, 2]], dtype=int32)>

In [ ]:
tensor1 *10

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[10, 20, 40],
       [20, 20, 20]], dtype=int32)>

In [ ]:
tensor1 - 10

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[-9, -8, -6],
       [-8, -8, -8]], dtype=int32)>

In [ ]:
10-tensor1

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[9, 8, 6],
       [8, 8, 8]], dtype=int32)>

In [ ]:
 # we can use the tensorflow built-in function too
import tensorflow as tf
tf.multiply(tensor1,10)
tf.add(tensor1,100)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[101, 102, 104],
       [102, 102, 102]], dtype=int32)>

In [ ]:
 # 018 matrix multipication with tensorr
t1=tf.constant([[2,2],[2,2]])
tf.matmul(t1,t1)  #matrix multipication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[8, 8],
       [8, 8]], dtype=int32)>

In [ ]:
t1.shape

TensorShape([2, 2])

In [ ]:
#matrix multipication using python operator
t1 @ t1 #python operator

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[8, 8],
       [8, 8]], dtype=int32)>

In [ ]:
# 019 matrix multiplication part 2
tf.reshape(t1,shape=(4,1))  # must have same no of values

<tf.Tensor: shape=(4, 1), dtype=int32, numpy=
array([[2],
       [2],
       [2],
       [2]], dtype=int32)>

In [ ]:
# can do the same with transpose
tf.transpose(t1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 2],
       [2, 2]], dtype=int32)>

In [ ]:
 # 020 matrix multiplication part 3
 # also called dot product
# tf.matmul()
# tf.tensordot()

# perform the dot product on x and y (require x or y to be transposed)
x=tf.constant([[1,2,3],[2,2,2],[2,2,3]])
y=tf.constant([[1,2,2],[2,5,6],[3,4,2]])
tf.tensordot(x,y,axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[14, 24, 20],
       [12, 22, 20],
       [15, 26, 22]], dtype=int32)>

In [ ]:
# generally, when performing matrix multiplicatoin on two tensors and one of
# the axes doesn;t line up , you will transpose (rather than reshape) one of the tensors 
# to get satisfy the matrix multiplication rules