In [ ]:
# 021 changing the datatype of tensors
import tensorflow as tf 
a=tf.constant([3,3])
a.dtype

tf.int32

In [ ]:
c=tf.constant([3.3,5.3])
c.dtype

# change from float32 to   float16
b=tf.cast(a,dtype=tf.float16) #same as we were using in other language
b.dtype

e=tf.cast(c,dtype=tf.int32)
e

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 5], dtype=int32)>

In [2]:
# 022 Tensor Aggregation : the collecting of units;
# aggregating tensors = condensing them from multiple values down to a smaller amount of values
# get the absoulte values
import tensorflow as tf
d=tf.constant([-2,3,3])
tf.abs(d)  # convert the negative to positive

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 3, 3], dtype=int32)>

In [ ]:
# lets go through the following forms of aggregation
# get the minimum , get the maximum , get the mean of tensor
import numpy as np
sri=tf.constant(np.random.randint(0,100,50))
sri

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([17, 10, 16, 14, 12, 60, 20, 75, 19, 51, 39, 47, 57, 32, 89, 20, 74,
       45, 63, 66, 62, 20,  7, 40, 14,  8, 31, 11, 25, 84,  5, 63,  7, 81,
       11, 31, 21, 19, 65,  1, 99,  8, 70, 53,  1, 70, 48, 40, 69,  1])>

In [ ]:
tf.size(sri),sri.shape, sri.ndim

(<tf.Tensor: shape=(), dtype=int32, numpy=50>, TensorShape([50]), 1)

In [ ]:
tf.reduce_min(sri)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

In [ ]:
tf.reduce_max(sri)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
tf.reduce_mean(sri)


<tf.Tensor: shape=(), dtype=int64, numpy=37>

In [ ]:
tf.reduce_sum(sri)

<tf.Tensor: shape=(), dtype=int64, numpy=1891>

In [ ]:
# 023 #find the variance of our tensor
import tensorflow_probability as tfp
tfp.stats.variance(sri)   # another way of finding the variance
tf.math.reduce_variance(sri)  

<tf.Tensor: shape=(), dtype=float32, numpy=739.5076>

In [ ]:
 # find the standard deviation
sri=tf.cast(sri,dtype=tf.float32)  # without this will get error because it must be complex or real numbers
tf.math.reduce_std(sri)


<tf.Tensor: shape=(), dtype=float32, numpy=27.19389>

In [ ]:
# 024 Find the positional maximum and minimum
# at which row or column we need to find the max or min
f=tf.random.uniform(shape=[50])
f

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6278926 , 0.5902896 , 0.7986189 , 0.5485302 , 0.5608592 ,
       0.07877839, 0.9026772 , 0.15769708, 0.85940623, 0.415195  ,
       0.22136688, 0.34981704, 0.7417823 , 0.9475242 , 0.5827975 ,
       0.9371083 , 0.60969484, 0.8982166 , 0.5047655 , 0.16373122,
       0.27312052, 0.79412436, 0.06647611, 0.5830643 , 0.9878583 ,
       0.5741838 , 0.39591885, 0.47772956, 0.7972739 , 0.30258298,
       0.8409531 , 0.671998  , 0.82779443, 0.24636626, 0.29815578,
       0.02402568, 0.9362283 , 0.7177187 , 0.707368  , 0.80709136,
       0.4175892 , 0.6650522 , 0.02613103, 0.984617  , 0.3786192 ,
       0.44650424, 0.35235226, 0.9755608 , 0.4697014 , 0.97826743],
      dtype=float32)>

In [ ]:
# find the positional maximum
tf.argmax(f)

<tf.Tensor: shape=(), dtype=int64, numpy=24>

In [ ]:
#index on our largest value position
f[tf.argmax(f)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9878583>

In [ ]:
assert f[tf.argmax(f)]==tf.reduce_max(f)

In [ ]:
tf.argmin(f)  # gives the minimum value position

<tf.Tensor: shape=(), dtype=int64, numpy=35>

In [ ]:
# 025 Squeezing a tensor (removing all single dimensions)
#create a tensor to get started
import tensorflow as tf
tf.random.set_seed(34)
g=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
g

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.7798102 , 0.03084028, 0.7501943 , 0.35165203, 0.2858461 ,
           0.06511438, 0.41808772, 0.6798382 , 0.2309972 , 0.38665044,
           0.897894  , 0.36882365, 0.57636   , 0.30526268, 0.8800684 ,
           0.4967736 , 0.61300397, 0.04011059, 0.81652415, 0.03450644,
           0.9478071 , 0.9286258 , 0.9282336 , 0.32839966, 0.36052978,
           0.31809175, 0.781394  , 0.71639967, 0.6259357 , 0.8604344 ,
           0.49752498, 0.6189635 , 0.9839041 , 0.36536515, 0.95524275,
           0.58393157, 0.93958735, 0.56482863, 0.9520861 , 0.7242578 ,
           0.53706086, 0.24300599, 0.8215152 , 0.50178564, 0.00776434,
           0.20443094, 0.48108208, 0.5146402 , 0.19926155, 0.0177567 ]]]]],
      dtype=float32)>

In [ ]:
g.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
g_squeezed=tf.squeeze(g)
g_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.7798102 , 0.03084028, 0.7501943 , 0.35165203, 0.2858461 ,
       0.06511438, 0.41808772, 0.6798382 , 0.2309972 , 0.38665044,
       0.897894  , 0.36882365, 0.57636   , 0.30526268, 0.8800684 ,
       0.4967736 , 0.61300397, 0.04011059, 0.81652415, 0.03450644,
       0.9478071 , 0.9286258 , 0.9282336 , 0.32839966, 0.36052978,
       0.31809175, 0.781394  , 0.71639967, 0.6259357 , 0.8604344 ,
       0.49752498, 0.6189635 , 0.9839041 , 0.36536515, 0.95524275,
       0.58393157, 0.93958735, 0.56482863, 0.9520861 , 0.7242578 ,
       0.53706086, 0.24300599, 0.8215152 , 0.50178564, 0.00776434,
       0.20443094, 0.48108208, 0.5146402 , 0.19926155, 0.0177567 ],
      dtype=float32)>

In [5]:
# 026 One hot encoding tensors - Is form of numerical encoding.(for more go to machine learning mastery website)
# create a list of indices
a=[4,3,2,1,0]
# one hot encode our list of indices
tf.one_hot(a,depth=4)  # if depth is less than the size of indices then it will not consider that

<tf.Tensor: shape=(5, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 1.],
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.]], dtype=float32)>

In [ ]:
# speicfy the custom values for one hot encoding
b=[2,1,0]
tf.one_hot(b,depth=3,on_value="blue is color",off_value="its green")

<tf.Tensor: shape=(3, 3), dtype=string, numpy=
array([[b'its green', b'its green', b'blue is color'],
       [b'its green', b'blue is color', b'its green'],
       [b'blue is color', b'its green', b'its green']], dtype=object)>

In [ ]:
# 027 trying out more tensor math operations
#squraing , log, square root
sri=tf.range(1,10)
sri

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
sq_sri=tf.square(sri)
sqr_sri=tf.math.sqrt(tf.cast(sri,dtype=tf.float32))
log_sri=tf.math.log(tf.cast(sri,dtype=tf.float32))
sq_sri, sqr_sri, log_sri

(<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>,
 <tf.Tensor: shape=(9,), dtype=float32, numpy=
 array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
        2.6457512, 2.828427 , 3.       ], dtype=float32)>,
 <tf.Tensor: shape=(9,), dtype=float32, numpy=
 array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
        1.9459102, 2.0794415, 2.1972246], dtype=float32)>)

In [ ]:
# 028 Exploring tensorflow and numpy compatibility
# tensorsflow interacts beautifully with numpy array
import numpy as np
fu=tf.constant(np.array([3,7,10]))
np.array(fu),type(np.array(fu)) #converting out tesnor back to a numpy array

(array([ 3,  7, 10]), numpy.ndarray)

In [ ]:
fu.numpy() ,type(fu.numpy()) # converting tensor fu to a numpy array

(array([ 3,  7, 10]), numpy.ndarray)

In [ ]:
j=tf.constant([3.])
j.numpy()[0]

3.0

In [ ]:
# the default types of each are slightly different
numpy_j=tf.constant(np.array([3,5,1]))
tensor_j=tf.constant([3,3,3,2])
numpy_j.dtype ,tensor_j.dtype  # both data are different

(tf.int64, tf.int32)

In [ ]:
# 029 Making sure our tensor operations run really fast on gpu
# Finding access to GPU
import tensorflow as tf
tf.config.list_physical_devices("CPU") 
# change to gpu by clicking on runtime and click change runtime type

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]

In [6]:
!nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [ ]:
# **Note if you have access to CUDA-enabled GPU , tensorflow will use it automaticlly ,use it whenever possible
